export const FORM_ERROR_CODES = [
  "TITLE_REQUIRED",
  "TITLE_TOO_LONG",
  "CONTENT_REQUIRED",
  "CONTENT_TOO_LONG",
  "CATEGORY_REQUIRED",
  "ANSWER_REQUIRED",
  "ANSWER_TOO_LONG",
  "QUESTION_NOT_FOUND",
  "QUESTION_SUBMIT_FAILED",
  "ANSWER_SUBMIT_FAILED",
] as const;

export type FormErrorCode = (typeof FORM_ERROR_CODES)[number];
